export const provinces = {
  ALAVA: { name: "Álava", slug: "alava" },
  ALBACETE: { name: "Albacete", slug: "albacete" },
  ALICANTE: { name: "Alicante", slug: "alicante" },
  ALMERIA: { name: "Almería", slug: "almeria" },
  A_CORUNA: { name: "A Coruña", slug: "a-coruna" },
  ASTURIAS: { name: "Asturias", slug: "asturias" },
  AVILA: { name: "Ávila", slug: "avila" },
  BADAJOZ: { name: "Badajoz", slug: "badajoz" },
  BALEARES: { name: "Baleares", slug: "baleares" },
  BARCELONA: { name: "Barcelona", slug: "barcelona" },
  BURGOS: { name: "Burgos", slug: "burgos" },
  CACERES: { name: "Cáceres", slug: "caceres" },
  CADIZ: { name: "Cádiz", slug: "cadiz" },
  CANTABRIA: { name: "Cantabria", slug: "cantabria" },
  CASTELLON: { name: "Castellón", slug: "castellon" },
  CIUDAD_REAL: { name: "Ciudad Real", slug: "ciudad-real" },
  CORDOBA: { name: "Córdoba", slug: "cordoba" },
  CUENCA: { name: "Cuenca", slug: "cuenca" },
  GIRONA: { name: "Girona", slug: "girona" },
  GRANADA: { name: "Granada", slug: "granada" },
  GUADALAJARA: { name: "Guadalajara", slug: "guadalajara" },
  GUIPUZCOA: { name: "Guipúzcoa", slug: "guipuzcoa" },
  HUELVA: { name: "Huelva", slug: "huelva" },
  HUESCA: { name: "Huesca", slug: "huesca" },
  JAEN: { name: "Jaén", slug: "jaen" },
  LA_RIOJA: { name: "La Rioja", slug: "la-rioja" },
  LAS_PALMAS: { name: "Las Palmas", slug: "las-palmas" },
  LEON: { name: "León", slug: "leon" },
  LLEIDA: { name: "Lleida", slug: "lleida" },
  LUGO: { name: "Lugo", slug: "lugo" },
  MADRID: { name: "Madrid", slug: "madrid" },
  MALAGA: { name: "Málaga", slug: "malaga" },
  MURCIA: { name: "Murcia", slug: "murcia" },
  NAVARRA: { name: "Navarra", slug: "navarra" },
  OURENSE: { name: "Ourense", slug: "ourense" },
  PALENCIA: { name: "Palencia", slug: "palencia" },
  PONTEVEDRA: { name: "Pontevedra", slug: "pontevedra" },
  SALAMANCA: { name: "Salamanca", slug: "salamanca" },
  SANTA_CRUZ_DE_TENERIFE: { name: "Santa Cruz de Tenerife", slug: "santa-cruz-de-tenerife" },
  SEGOVIA: { name: "Segovia", slug: "segovia" },
  SEVILLA: { name: "Sevilla", slug: "sevilla" },
  SORIA: { name: "Soria", slug: "soria" },
  TARRAGONA: { name: "Tarragona", slug: "tarragona" },
  TERUEL: { name: "Teruel", slug: "teruel" },
  TOLEDO: { name: "Toledo", slug: "toledo" },
  VALENCIA: { name: "Valencia", slug: "valencia" },
  VALLADOLID: { name: "Valladolid", slug: "valladolid" },
  VIZCAYA: { name: "Vizcaya", slug: "vizcaya" },
  ZAMORA: { name: "Zamora", slug: "zamora" },
  ZARAGOZA: { name: "Zaragoza", slug: "zaragoza" },
} as const;
