import { Lookup } from "@/common/models";

export const PROVINCIAS: Lookup[] = [
  { id: "alava", name: "Álava" },
  { id: "albacete", name: "Albacete" },
  { id: "alicante", name: "Alicante" },
  { id: "almeria", name: "Almería" },
  { id: "asturias", name: "Asturias" },
  { id: "avila", name: "Ávila" },
  { id: "badajoz", name: "Badajoz" },
  { id: "baleares", name: "Baleares" },
  { id: "barcelona", name: "Barcelona" },
  { id: "burgos", name: "Burgos" },
  { id: "caceres", name: "Cáceres" },
  { id: "cadiz", name: "Cádiz" },
  { id: "cantabria", name: "Cantabria" },
  { id: "castellon", name: "Castellón" },
  { id: "ciudad-real", name: "Ciudad Real" },
  { id: "cordoba", name: "Córdoba" },
  { id: "la-coruna", name: "La Coruña" },
  { id: "cuenca", name: "Cuenca" },
  { id: "girona", name: "Girona" },
  { id: "granada", name: "Granada" },
  { id: "guadalajara", name: "Guadalajara" },
  { id: "guipuzcoa", name: "Guipúzcoa" },
  { id: "huelva", name: "Huelva" },
  { id: "huesca", name: "Huesca" },
  { id: "jaen", name: "Jaén" },
  { id: "la-rioja", name: "La Rioja" },
  { id: "las-palmas", name: "Las Palmas" },
  { id: "leon", name: "León" },
  { id: "lleida", name: "Lleida" },
  { id: "lugo", name: "Lugo" },
  { id: "madrid", name: "Madrid" },
  { id: "malaga", name: "Málaga" },
  { id: "murcia", name: "Murcia" },
  { id: "navarra", name: "Navarra" },
  { id: "ourense", name: "Ourense" },
  { id: "palencia", name: "Palencia" },
  { id: "pontevedra", name: "Pontevedra" },
  { id: "salamanca", name: "Salamanca" },
  { id: "santa-cruz-de-tenerife", name: "Santa Cruz de Tenerife" },
  { id: "segovia", name: "Segovia" },
  { id: "sevilla", name: "Sevilla" },
  { id: "soria", name: "Soria" },
  { id: "tarragona", name: "Tarragona" },
  { id: "teruel", name: "Teruel" },
  { id: "toledo", name: "Toledo" },
  { id: "valencia", name: "Valencia" },
  { id: "valladolid", name: "Valladolid" },
  { id: "vizcaya", name: "Vizcaya" },
  { id: "zamora", name: "Zamora" },
  { id: "zaragoza", name: "Zaragoza" },
];
