import {
  A_CORUNA,
  ALAVA,
  ALBACETE,
  ALICANTE,
  ALMERIA,
  ASTURIAS,
  AVILA,
  BADAJOZ,
  BARCELONA,
  BURGOS,
  CACERES,
  CADIZ,
  CANTABRIA,
  CASTELLON,
  CIUDAD_REAL,
  CORDOBA,
  CUENCA,
  GIRONA,
  GRANADA,
  GUADALAJARA,
  GUIPUZCOA,
  HUELVA,
  HUESCA,
  JAEN,
  LA_RIOJA,
  LEON,
  LLEIDA,
  LUGO,
  MADRID,
  MALAGA,
  MURCIA,
  NAVARRA,
  OURENSE,
  PALENCIA,
  PONTEVEDRA,
  SALAMANCA,
  SEGOVIA,
  SEVILLA,
  SORIA,
  TARRAGONA,
  TERUEL,
  TOLEDO,
  VALENCIA,
  VALLADOLID,
  VIZCAYA,
  ZAMORA,
  ZARAGOZA,
} from "db-model";

export const embalseProvincias = new Map<string, string>([
  ["acena", AVILA],
  ["agavanzal-n-a-s-a-de", ZAMORA],
  ["agrio-aznalcollar", SEVILLA],
  ["aguascebas", JAEN],
  ["agueda", SALAMANCA],
  ["aguijon-el", BADAJOZ],
  ["aguilar", PALENCIA],
  ["alange", BADAJOZ],
  ["alarcon", CUENCA],
  ["albarellos", OURENSE],
  ["albina", ALAVA],
  ["alcala-del-rio", SEVILLA],
  ["alcaniz-estanca", TERUEL],
  ["alcantara", CACERES],
  ["alcollarin", CACERES],
  ["alcorlo", GUADALAJARA],
  ["aldeadavila", SALAMANCA],
  ["alfilorios", ASTURIAS],
  ["alfonso-xiii", MURCIA],
  ["algar", VALENCIA],
  ["algeciras", MURCIA],
  ["alloz", NAVARRA],
  ["almendra", SALAMANCA],
  ["almodovar", CADIZ],
  ["almoguera", GUADALAJARA],
  ["alsa-mediajo", CANTABRIA],
  ["amadorio", ALICANTE],
  ["anarbe", GUIPUZCOA],
  ["anchuricas", JAEN],
  ["andevalo", HUELVA],
  ["aracena", HUELVA],
  ["arbon", ASTURIAS],
  ["arcos-de-la-frontera", CADIZ],
  ["arenos", CASTELLON],
  ["arenoso", CORDOBA],
  ["argos", MURCIA],
  ["arlanzon", BURGOS],
  ["arquillo-de-san-blas", TERUEL],
  ["atance-el", GUADALAJARA],
  ["atazar-el", MADRID],
  ["azutan", TOLEDO],
  ["bachimana-lago", HUESCA],
  ["banos", CACERES],
  ["bao", OURENSE],
  ["barasona", HUESCA],
  ["barbate", CADIZ],
  ["barca-la", CANTABRIA],
  ["barcena", LEON],
  ["barrie-de-la-maza", A_CORUNA],
  ["barrios-de-luna", LEON],
  ["baserca", HUESCA],
  ["belena", GUADALAJARA],
  ["belesar", LUGO],
  ["bellus", VALENCIA],
  ["bembezar", CORDOBA],
  ["benageber", VALENCIA],
  ["beniarres", ALICANTE],
  ["beninar", ALMERIA],
  ["bermejales", GRANADA],
  ["beznar", GRANADA],
  ["boadella", GIRONA],
  ["bolarque", GUADALAJARA],
  ["bolera-la", JAEN],
  ["boqueron", BADAJOZ],
  ["borbollon", CACERES],
  ["bornos", CADIZ],
  ["bramatuero-alto", HUESCA],
  ["brena-ii-la", CORDOBA],
  ["brena-la", CORDOBA],
  ["brovales", BADAJOZ],
  ["bubal", HUESCA],
  ["buendia", GUADALAJARA],
  ["burdalo", CACERES],
  ["burgomillodo", SEGOVIA],
  ["burguillo-puente-nuevo", AVILA],
  ["buseo", VALENCIA],
  ["caceres-guadiloba", CACERES],
  ["cala", SEVILLA],
  ["calanda", TERUEL],
  ["camarasa", LLEIDA],
  ["camarillas", ALBACETE],
  ["campanana-la", LEON],
  ["camporredondo", PALENCIA],
  ["canales", GRANADA],
  ["canchales", BADAJOZ],
  ["cancho-del-fresno", CACERES],
  ["canelles", HUESCA],
  ["canon-de-santolea", TERUEL],
  ["cantillana", SEVILLA],
  ["carpio-el", CORDOBA],
  ["casares-de-arbas", LEON],
  ["casasola", MALAGA],
  ["caspe", ZARAGOZA],
  ["castilseras", CIUDAD_REAL],
  ["castrejon", TOLEDO],
  ["castrelo", OURENSE],
  ["castro", ZAMORA],
  ["castro-de-las-cogotas", AVILA],
  ["castro-el", TOLEDO],
  ["catllar", TARRAGONA],
  ["cavallers", LLEIDA],
  ["cazalegas", TOLEDO],
  ["cecebre", A_CORUNA],
  ["cedillo", CACERES],
  ["celemin", CADIZ],
  ["cenajo", ALBACETE],
  ["cenza", OURENSE],
  ["cernadilla", ZAMORA],
  ["certescans", LLEIDA],
  ["cervera", PALENCIA],
  ["chandrexa", OURENSE],
  ["chanza", HUELVA],
  ["charco-redondo", CADIZ],
  ["cierva-la", MURCIA],
  ["cijara", BADAJOZ],
  ["ciurana", TARRAGONA],
  ["cohilla-la", CANTABRIA],
  ["colomera", GRANADA],
  ["compuerto", PALENCIA],
  ["concepcion", MALAGA],
  ["conchas-las", OURENSE],
  ["conde-guadalhorce", MALAGA],
  ["contreras", CUENCA],
  ["cordobilla", CORDOBA],
  ["cornalbo", BADAJOZ],
  ["cortes-ii", VALENCIA],
  ["corumbel-bajo", HUELVA],
  ["crevillente", ALICANTE],
  ["cubilar", CACERES],
  ["cubillas", GRANADA],
  ["cuerda-del-pozo", SORIA],
  ["cueva-foradada", TERUEL],
  ["cuevas-de-almanzora", ALMERIA],
  ["derivacion-retortillo", CORDOBA],
  ["doiras", ASTURIAS],
  ["dona-aldonza", JAEN],
  ["ebro", CANTABRIA],
  ["edrada-mao", OURENSE],
  ["eiras", PONTEVEDRA],
  ["el-naranjero", VALENCIA],
  ["el-portillo", GRANADA],
  ["el-vicario", CIUDAD_REAL],
  ["encinarejo", JAEN],
  ["enciso", LA_RIOJA],
  ["entrepenas", GUADALAJARA],
  ["escales", HUESCA],
  ["escalona", VALENCIA],
  ["escarra", HUESCA],
  ["eugui", NAVARRA],
  ["eume", A_CORUNA],
  ["fernandina-la", JAEN],
  ["fervenza", A_CORUNA],
  ["finisterre", TOLEDO],
  ["foix", BARCELONA],
  ["forata", VALENCIA],
  ["forcadas-as", A_CORUNA],
  ["francisco-abellan", GRANADA],
  ["fresneda", CIUDAD_REAL],
  ["frieira", PONTEVEDRA],
  ["fuensanta", ALBACETE],
  ["gabriel-y-galan", CACERES],
  ["garcia-de-sola", BADAJOZ],
  ["gargaligas", BADAJOZ],
  ["gasset", CIUDAD_REAL],
  ["gergal", SEVILLA],
  ["giribaile", JAEN],
  ["gonzalez-lacasa", LA_RIOJA],
  ["grado-el", HUESCA],
  ["guadalcacin-ii", CADIZ],
  ["guadalen", JAEN],
  ["guadalest", ALICANTE],
  ["guadalhorce-guadalteba", MALAGA],
  ["guadalmellato", CORDOBA],
  ["guadalmena", JAEN],
  ["guadarranque", CADIZ],
  ["guajaraz", TOLEDO],
  ["guiamets", TARRAGONA],
  ["guijo-de-granadilla", CACERES],
  ["guillena", SEVILLA],
  ["guistolas", OURENSE],
  ["hornachuelos", CORDOBA],
  ["horno-tejero", BADAJOZ],
  ["huesna", SEVILLA],
  ["hurones-los", CADIZ],
  ["ibai-eder", GUIPUZCOA],
  ["ibiur", GUIPUZCOA],
  ["ip", HUESCA],
  ["irabia", NAVARRA],
  ["iruena", SALAMANCA],
  ["itoiz", NAVARRA],
  ["iznajar", CORDOBA],
  ["jandula", JAEN],
  ["jarosa-la", MADRID],
  ["jarrama", HUELVA],
  ["jerte-plasencia", CACERES],
  ["jose-toran", SEVILLA],
  ["la-baells", BARCELONA],
  ["la-cabezuela", CIUDAD_REAL],
  ["la-colada", CORDOBA],
  ["la-llosa-del-cavall", LLEIDA],
  ["la-muela", VALENCIA],
  ["la-pedrera", ALICANTE],
  ["la-serena", BADAJOZ],
  ["la-toba", CUENCA],
  ["lanuza", HUESCA],
  ["las-fitas", HUESCA],
  ["laverne", ZARAGOZA],
  ["lechago", TERUEL],
  ["limonero", MALAGA],
  ["linares-del-arroyo", SEGOVIA],
  ["llauset", HUESCA],
  ["llerena", BADAJOZ],
  ["loriguilla", VALENCIA],
  ["los-machos", HUELVA],
  ["los-molinos", BADAJOZ],
  ["loteta-la", ZARAGOZA],
  ["maidevera", ZARAGOZA],
  ["malpasillo-jauja", CORDOBA],
  ["mansilla", LA_RIOJA],
  ["mar-lago", LLEIDA],
  ["maria-cristina", CASTELLON],
  ["marmolejo", JAEN],
  ["martin-gonzalo", CORDOBA],
  ["matalavilla", LEON],
  ["mediano", HUESCA],
  ["melonares-los", SEVILLA],
  ["mequinenza", ZARAGOZA],
  ["minilla-la", SEVILLA],
  ["molino-de-chincha", CUENCA],
  ["moneva", ZARAGOZA],
  ["monteagudo", SORIA],
  ["montearagon", HUESCA],
  ["montefurado", LUGO],
  ["montijo", BADAJOZ],
  ["montoro", CIUDAD_REAL],
  ["nagore", NAVARRA],
  ["navacerrada", MADRID],
  ["navalcan", TOLEDO],
  ["navamuno", SALAMANCA],
  ["negratin", GRANADA],
  ["negro-lago", LLEIDA],
  ["nogales", BADAJOZ],
  ["odiel", HUELVA],
  ["oliana", LLEIDA],
  ["olivargas", HUELVA],
  ["ordunte", BURGOS],
  ["orellana", BADAJOZ],
  ["pajares", LA_RIOJA],
  ["palmaces", GUADALAJARA],
  ["pardo-el", MADRID],
  ["parras-las", TERUEL],
  ["peares-os", LUGO],
  ["pedro-marin", JAEN],
  ["pena", TERUEL],
  ["pena-la", HUESCA],
  ["penarroya", CIUDAD_REAL],
  ["penarrubia", OURENSE],
  ["pias-san-agustin", OURENSE],
  ["picadas", MADRID],
  ["piedra-aguda", BADAJOZ],
  ["piedras", HUELVA],
  ["pinilla", MADRID],
  ["pintado-el", SEVILLA],
  ["ponton-alto-el", SEGOVIA],
  ["porma-juan-benet", LEON],
  ["portaje", CACERES],
  ["portas-las", OURENSE],
  ["portina-la", TOLEDO],
  ["portodemouros", PONTEVEDRA],
  ["prada", OURENSE],
  ["proserpina", BADAJOZ],
  ["pto-vallehermoso", CIUDAD_REAL],
  ["puebla-de-cazalla", SEVILLA],
  ["puente-de-santolea", TERUEL],
  ["puente-nuevo", CORDOBA],
  ["puente-porto", ZAMORA],
  ["puentes", MURCIA],
  ["puentes-viejas", MADRID],
  ["quentar", GRANADA],
  ["quiebrajano", JAEN],
  ["rabanos", SORIA],
  ["regajo", CASTELLON],
  ["requejada", PALENCIA],
  ["respomuso", HUESCA],
  ["retortillo", CORDOBA],
  ["rialb", LLEIDA],
  ["riano", LEON],
  ["ribarroja", TARRAGONA],
  ["ribeira-a", A_CORUNA],
  ["ricobayo", ZAMORA],
  ["riocobo", LUGO],
  ["rioseco", ASTURIAS],
  ["riosequillo", MADRID],
  ["riudecanyes", TARRAGONA],
  ["rivera-de-gata", CACERES],
  ["rosarito", TOLEDO],
  ["rozas-las", LEON],
  ["ruecas", CACERES],
  ["rules", GRANADA],
  ["rumblar", JAEN],
  ["saburo-lago", LLEIDA],
  ["salas", OURENSE],
  ["salime", ASTURIAS],
  ["sallente", LLEIDA],
  ["salor", CACERES],
  ["san-anton", NAVARRA],
  ["san-bartolome", ZARAGOZA],
  ["san-clemente", GRANADA],
  ["san-jose", VALLADOLID],
  ["san-juan", MADRID],
  ["san-lorenzo", LLEIDA],
  ["san-martino", OURENSE],
  ["san-pedro", LUGO],
  ["san-rafael-de-navallana", CORDOBA],
  ["san-salvador", HUESCA],
  ["san-sebastian", ZAMORA],
  ["san-estevo", OURENSE],
  ["sancho", HUELVA],
  ["sant-pons", LLEIDA],
  ["santa-ana", HUESCA],
  ["santa-eulalia", OURENSE],
  ["santa-maria-de-belsue", HUESCA],
  ["santa-teresa", SALAMANCA],
  ["santillana", MADRID],
  ["santolea", TERUEL],
  ["santomera", MURCIA],
  ["sau", BARCELONA],
  ["saucelle", SALAMANCA],
  ["sequeiros", LUGO],
  ["serones", AVILA],
  ["sichar", CASTELLON],
  ["sierra-boyera", CORDOBA],
  ["sierra-brava", CACERES],
  ["siles", JAEN],
  ["sistema-aguas-limpias", HUESCA],
  ["sistema-alto-caldares", HUESCA],
  ["sistema-capdella", LLEIDA],
  ["sistema-escarra", HUESCA],
  ["sistema-lagos-espot", LLEIDA],
  ["sistema-valle-de-aran", LLEIDA],
  ["sobron", BURGOS],
  ["somiedo-lagos", ASTURIAS],
  ["sotonera", HUESCA],
  ["sta-uxia", A_CORUNA],
  ["susqueda", GIRONA],
  ["taibilla", ALBACETE],
  ["tajera-la", GUADALAJARA],
  ["talave", ALBACETE],
  ["tanes", ASTURIAS],
  ["tentudia", BADAJOZ],
  ["terradets", LLEIDA],
  ["terroba", LA_RIOJA],
  ["torcas-las", ZARAGOZA],
  ["torcon", TOLEDO],
  ["torre-de-abraham", CIUDAD_REAL],
  ["torre-del-aguila", SEVILLA],
  ["torrejon-tajo-tietar", CACERES],
  ["tort-lago", LLEIDA],
  ["tous-la-ribera", VALENCIA],
  ["tranco-de-beas", JAEN],
  ["tranquera-la", ZARAGOZA],
  ["tremp-o-talarn", LLEIDA],
  ["ulldecona", CASTELLON],
  ["ullivarri", ALAVA],
  ["urdalur", NAVARRA],
  ["urdiceto", HUESCA],
  ["urkulu", GUIPUZCOA],
  ["urrunaga", ALAVA],
  ["uzquiza", BURGOS],
  ["vadiello", HUESCA],
  ["vado-el", GUADALAJARA],
  ["vadomojon", CORDOBA],
  ["val-el", ZARAGOZA],
  ["valdecanas", CACERES],
  ["valdeinfierno", MURCIA],
  ["valdeobispo", CACERES],
  ["valdepatao", HUESCA],
  ["valmayor", MADRID],
  ["valparaiso", ZAMORA],
  ["valuengo", BADAJOZ],
  ["vega-del-jabalon", CIUDAD_REAL],
  ["velle", OURENSE],
  ["vellon-el-pedrezuela", MADRID],
  ["vencias-las", SEGOVIA],
  ["viboras", JAEN],
  ["vilasouto", LUGO],
  ["villafranca", CORDOBA],
  ["villagonzalo", SALAMANCA],
  ["villagudin", A_CORUNA],
  ["villalba-de-los-barros", BADAJOZ],
  ["villalcampo", ZAMORA],
  ["villameca", LEON],
  ["villar-del-rey", BADAJOZ],
  ["villar-el", MADRID],
  ["vinuela-la", MALAGA],
  ["yeguas", CORDOBA],
  ["yesa", NAVARRA],
  ["zahara-el-gastor", CADIZ],
  ["zocueca", JAEN],
  ["zufre", HUELVA],
  ["zujar", BADAJOZ],
]);
